# basic options
plugins:
  - jekyll-feed
title: Developer Blog
author: Dmitry Samoylenko
email: samoylenkodmitry@gmail.com
description: This is a personal blog. Mail me if you want to use materials from it.
twitter_username: DmitrySamoylenk
github_username:  s-a--m
linkedin: dmitrysamoylenko
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: true

disqus: 
  shortname: http-dmitrysamoylenko-com
# Build settings
markdown: kramdown
theme: minima
