# basic options
title: Developer Blog
author: Dmitry Samoylenko
email: mail@dmitrysamoylenko.com
description: some thougths
twitter_username: jekyllrb
github_username:  s-a--m

# Build settings
markdown: kramdown
theme: minima
