# basic options
title: Developer Blog
author: Dmitry Samoylenko
email: mail@dmitrysamoylenko.com
description: This is a personal blog. Mail me if you want to use materials from it.
twitter_username: DmitrySamoylenk
github_username:  s-a--m
linkedin: dmitrysamoylenko
  disqus:
    shortname: disqus_g6Deh1vTol
# Build settings
markdown: kramdown
theme: minima
